apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-twgt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-twgt
    app.kubernetes.io/part-of: tkrw-pr712-0075-0019-app
  name: devfile-sample-twgt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-twgt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-twgt
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-twgt@sha256:b3d9b46a76f8b533a0540b07b36f046bb19564c8dc67025453da5c59e5a41384
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
